apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.26.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      - name: multitool-container
        image: wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: HTTP_PORT
      volumes:
      - name: nginx-html
        configMap:
          name: my-config
          items:
          - key: index.html
            path: index.html
