apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  HTTP_PORT: "1180"
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My homework for Netology</title>
    </head>
    <body>
        <h1>K8s homework</h1>
        <p>This is a test page to demonstrate how applications work in k8s.</p>
    </body>
    </html>